'use client'

import { useState } from 'react'
import { X, Copy, Check, Mail, Users, FileText, Share2, Sparkles } from 'lucide-react'

interface CombatResult {
  phase: 'diagnosis' | 'treatment'
  question: string
  perspectives: {
    name: string
    icon: string
    color: string
    argument: string
    evidence: string[]
    confidence: number
    recommendation: string
  }[]
  synthesis: string
  consensus: string[]
  divergence: string[]
  questionsForOncologist?: string[]
  recommendedTests?: string[]
  nextSteps?: string[]
}

interface ShareModalProps {
  isOpen: boolean
  onClose: () => void
  shareType: 'oncologist' | 'family' | 'self'
  result: CombatResult
  cancerType?: string
  recordsCount: number
}

export function ShareModal({ isOpen, onClose, shareType, result, cancerType, recordsCount }: ShareModalProps) {
  const [copied, setCopied] = useState(false)
  const [emailAddress, setEmailAddress] = useState('')
  const [familyName, setFamilyName] = useState('')
  const [personalNote, setPersonalNote] = useState('')

  if (!isOpen) return null

  // Generate the viral link with referral
  const viralLink = `https://opencancer.ai/combat?ref=family`

  // Generate subject lines
  const getSubject = () => {
    switch (shareType) {
      case 'oncologist':
        return `CancerCombat Analysis: ${result.phase === 'diagnosis' ? 'Diagnosis' : 'Treatment'} Review - ${cancerType || 'Patient Case'}`
      case 'family':
        return `Sharing my cancer analysis with you`
      case 'self':
        return `My CancerCombat Analysis - ${new Date().toLocaleDateString()}`
    }
  }

  // Generate oncologist email body (professional)
  const getOncologistBody = () => `
Dear Doctor,

I used an AI-powered tool called CancerCombat to analyze my medical records from three clinical perspectives (NCCN Guidelines, Emerging Research, and Integrative Oncology). I wanted to share this analysis with you to help guide our next conversation.

CLINICAL QUESTION ANALYZED:
${result.question}

SUMMARY OF PERSPECTIVES:

${result.perspectives.map(p => `• ${p.name} (${p.confidence}% confidence):
  ${p.recommendation}
`).join('\n')}

AREAS OF CONSENSUS:
${result.consensus.map(c => `• ${c}`).join('\n')}

AREAS OF DIVERGENCE:
${result.divergence.map(d => `• ${d}`).join('\n')}

SYNTHESIS:
${result.synthesis}

${result.questionsForOncologist ? `
QUESTIONS I'D LIKE TO DISCUSS:
${result.questionsForOncologist.map((q, i) => `${i + 1}. ${q}`).join('\n')}
` : ''}

I understand this AI analysis is meant to support, not replace, clinical decision-making. I look forward to discussing these perspectives with you.

Best regards,
[Your Name]

---
Analysis generated by CancerCombat at opencancer.ai
Based on ${recordsCount} medical record${recordsCount !== 1 ? 's' : ''}
Sources: NCCN Guidelines 2025, PubMed, ClinicalTrials.gov
`.trim()

  // Generate family email body (simplified + viral)
  const getFamilyBody = () => `
Hi${familyName ? ` ${familyName}` : ''},

${personalNote || `I wanted to share something I've been using to better understand my cancer diagnosis and treatment options.`}

I used a tool called CancerCombat that analyzes my medical records from three different expert perspectives. Here's what I learned:

THE QUESTION I EXPLORED:
${result.question}

WHAT THE EXPERTS AGREED ON:
${result.consensus.map(c => `✓ ${c}`).join('\n')}

THE BOTTOM LINE:
${result.synthesis}

NEXT STEPS WE'RE DISCUSSING:
${result.nextSteps?.map(s => `• ${s}`).join('\n') || `• Review with my oncologist\n• Discuss the options together\n• Make a decision as a team`}

${result.divergence.length > 0 ? `
THINGS THAT AREN'T CLEAR-CUT:
${result.divergence.map(d => `• ${d}`).join('\n')}
` : ''}

---

I thought you might find this helpful too. CancerCombat lets you upload medical records and get AI analysis from multiple perspectives - it's been really helpful for understanding my options.

👉 Try it yourself: ${viralLink}

It's free to use, and I think it could help anyone navigating a health journey.

With love,
[Your Name]

---
📧 Powered by opencancer.ai
🤖 CancerCombat: 3 AI perspectives on your cancer case
`.trim()

  // Generate self email body
  const getSelfBody = () => `
My CancerCombat Analysis
Saved on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

${'='.repeat(50)}

${result.phase.toUpperCase()} ANALYSIS

QUESTION:
${result.question}

THREE PERSPECTIVES:

${result.perspectives.map(p => `
${p.name.toUpperCase()} (${p.confidence}% confidence)
${'-'.repeat(40)}
${p.recommendation}

Supporting Evidence:
${p.evidence.map((e, i) => `${i + 1}. ${e}`).join('\n')}
`).join('\n')}

SYNTHESIS:
${result.synthesis}

WHERE EXPERTS AGREE:
${result.consensus.map(c => `✓ ${c}`).join('\n')}

WHERE THEY DIVERGE:
${result.divergence.map(d => `• ${d}`).join('\n')}

${result.questionsForOncologist ? `
QUESTIONS FOR MY ONCOLOGIST:
${result.questionsForOncologist.map((q, i) => `${i + 1}. ${q}`).join('\n')}
` : ''}

${result.recommendedTests ? `
TESTS TO DISCUSS:
${result.recommendedTests.map(t => `• ${t}`).join('\n')}
` : ''}

---
Saved from CancerCombat at opencancer.ai
Based on ${recordsCount} medical record${recordsCount !== 1 ? 's' : ''}
`.trim()

  const getBody = () => {
    switch (shareType) {
      case 'oncologist': return getOncologistBody()
      case 'family': return getFamilyBody()
      case 'self': return getSelfBody()
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(getBody())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleSendEmail = () => {
    const subject = encodeURIComponent(getSubject())
    const body = encodeURIComponent(getBody())
    const to = emailAddress ? encodeURIComponent(emailAddress) : ''
    window.open(`mailto:${to}?subject=${subject}&body=${body}`)
    onClose()
  }

  const configs = {
    oncologist: {
      icon: FileText,
      title: 'Share with Your Oncologist',
      subtitle: 'Professional clinical summary',
      gradient: 'from-blue-500 to-blue-600',
      showName: false,
      showNote: false,
    },
    family: {
      icon: Users,
      title: 'Share with Family',
      subtitle: 'Simplified summary + invite to try CancerCombat',
      gradient: 'from-emerald-500 to-teal-500',
      showName: true,
      showNote: true,
    },
    self: {
      icon: Mail,
      title: 'Email to Myself',
      subtitle: 'Save this analysis for later',
      gradient: 'from-violet-500 to-fuchsia-500',
      showName: false,
      showNote: false,
    },
  }

  const config = configs[shareType]
  const Icon = config.icon

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={onClose} />

      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl max-w-lg w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className={`bg-gradient-to-r ${config.gradient} p-5`}>
          <button
            onClick={onClose}
            className="absolute top-4 right-4 text-white/80 hover:text-white"
          >
            <X className="w-5 h-5" />
          </button>
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center">
              <Icon className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">{config.title}</h2>
              <p className="text-white/80 text-sm">{config.subtitle}</p>
            </div>
          </div>
        </div>

        {/* Body */}
        <div className="p-5 space-y-4 overflow-y-auto flex-1">
          {/* Email field */}
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">
              {shareType === 'oncologist' ? "Your oncologist's email" : shareType === 'family' ? "Family member's email" : "Your email"}
            </label>
            <input
              type="email"
              value={emailAddress}
              onChange={(e) => setEmailAddress(e.target.value)}
              placeholder={shareType === 'oncologist' ? 'oncologist@hospital.com' : 'email@example.com'}
              className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
            />
          </div>

          {/* Family name (only for family share) */}
          {config.showName && (
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">
                Their name (optional)
              </label>
              <input
                type="text"
                value={familyName}
                onChange={(e) => setFamilyName(e.target.value)}
                placeholder="Mom, Dad, Sarah..."
                className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500"
              />
            </div>
          )}

          {/* Personal note (only for family share) */}
          {config.showNote && (
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">
                Add a personal note (optional)
              </label>
              <textarea
                value={personalNote}
                onChange={(e) => setPersonalNote(e.target.value)}
                placeholder="I've been using this tool to understand my diagnosis better..."
                rows={2}
                className="w-full px-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-violet-500 resize-none"
              />
            </div>
          )}

          {/* Viral invite banner (only for family share) */}
          {shareType === 'family' && (
            <div className="bg-gradient-to-r from-orange-50 to-amber-50 border border-orange-200 rounded-xl p-4">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-orange-400 to-amber-400 flex items-center justify-center flex-shrink-0">
                  <Share2 className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="font-semibold text-slate-900 text-sm">Spread the word!</p>
                  <p className="text-xs text-slate-600 mt-0.5">
                    Your email will include an invite for them to try CancerCombat too. Help others navigate their health journey.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Preview */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-slate-700">Email Preview</label>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-xs text-violet-600 hover:text-violet-700"
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 max-h-48 overflow-y-auto">
              <pre className="text-xs text-slate-600 whitespace-pre-wrap font-sans">
                {getBody()}
              </pre>
            </div>
          </div>

          {/* @opencancer.ai CTA - Coming Soon */}
          <div className="bg-gradient-to-r from-slate-50 to-slate-100 border border-slate-200 rounded-xl p-4">
            <div className="flex items-start justify-between gap-3">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="w-4 h-4 text-slate-400" />
                  <span className="text-xs font-bold text-slate-500 bg-slate-200 px-2 py-0.5 rounded-full">COMING SOON</span>
                </div>
                <p className="text-sm text-slate-600">
                  Get your own <span className="font-medium text-slate-700">you@opencancer.ai</span> email.
                  Forward medical documents there and they'll appear in your Records Vault!
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-5 border-t border-slate-200 bg-slate-50">
          <div className="flex gap-3">
            <button
              onClick={onClose}
              className="px-4 py-2.5 border border-slate-200 text-slate-700 rounded-lg font-medium hover:bg-white transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleCopy}
              className="flex-1 px-4 py-2.5 border border-slate-300 text-slate-700 rounded-lg font-medium hover:bg-white transition-colors flex items-center justify-center gap-2"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
            <button
              onClick={handleSendEmail}
              className={`flex-1 px-4 py-2.5 bg-gradient-to-r ${config.gradient} text-white rounded-lg font-semibold hover:opacity-90 transition-all flex items-center justify-center gap-2`}
            >
              <Mail className="w-4 h-4" />
              Open Email App
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
